import Math
print("Addition Test")
Math.addition()
print("IsEven Test")
Math.iseven()
print("Multiplication Test")
Math.multiplication()
print("Subtraction Test")
Math.subtraction()
print("Division Test")
Math.division()
print ("All Tests concluded")
